- hosts: localhost
  become: yes

  tasks:

    - name: Create new dir for matomo script
      file:
        path: /backup/matomodb/scripts
        state: directory
        owner: root
        group: root
        mode: 0700

    # Copy matomo script to remote machine
    - copy:
        src:  /etc/ansible/scripts/matomo_mysql_bck.sh
        dest: /backup/matomodb/scripts
        owner: root
        group: root
        mode: 0755

    #Create cronjob to run script to run @5:00
    - name: Create cronjob to for db dump and backup
      cron:
        name: run matomo backup
        user: root
        hour: 5
        minute: 0
        job: "/bin/sh /backup/matomodb/scripts/matomo_mysql_bck.sh"
        state: present
